export type ProjectCategory = "frontend" | "fullstack" | "security";

export interface Project {
  num: string;
  slug: string;
  name: string;
  desc: string;
  tech: string[];
  year: string;
  category: ProjectCategory;
  gradient: string;
  repo: string;
  live?: string;
  /** Screenshot under /public — cards without one render a branded placeholder. */
  image?: string;
}

export const projects: Project[] = [
  {
    num: "01",
    slug: "certwatch",
    name: "CertWatch",
    desc: "SaaS dashboard that watches your SSL certificates so you don't have to — expiry tracking, health monitoring, and proactive alerts that stop downtime before it starts.",
    tech: ["Next.js", "TypeScript", "Supabase", "Tailwind"],
    year: "2026",
    category: "fullstack",
    gradient: "linear-gradient(135deg, #1a1a2e, #16213e)",
    repo: "https://github.com/vinamra1102/CertWatch-certificate_checker-Frontend-",
    live: "https://cert-watch-certificate-checker-fron.vercel.app",
    image: "/projects/certwatch.png",
  },
  {
    num: "02",
    slug: "web-vulnerability-scanner",
    name: "Web Vulnerability Scanner",
    desc: "Python-powered scanner that hunts SQL injection, XSS, and insecure HTTP headers across web apps — actionable findings, not noise.",
    tech: ["Python", "TypeScript", "Security"],
    year: "2025",
    category: "security",
    gradient: "linear-gradient(135deg, #2e1a1a, #3e2121)",
    repo: "https://github.com/vinamra1102/webVulnerabilityScanner",
  },
  {
    num: "03",
    slug: "her-ecom",
    name: "Her-Ecom",
    desc: "Modern e-commerce experience in Next.js — dynamic product pages, instant cart state with Zustand, and a shopping flow that feels effortless on any screen.",
    tech: ["Next.js", "TypeScript", "Zustand"],
    year: "2026",
    category: "frontend",
    gradient: "linear-gradient(135deg, #1a0a00, #2d1000)",
    repo: "https://github.com/vinamra1102/Her-Ecom",
  },
  {
    num: "04",
    slug: "hydrolock",
    name: "HydroLock",
    desc: "Rule-based app locker that makes habits the key — real-world tasks like hydration events become unlock conditions for your apps.",
    tech: ["React", "TypeScript", "Supabase", "Vite"],
    year: "2026",
    category: "fullstack",
    gradient: "linear-gradient(135deg, #0a1420, #12293c)",
    repo: "https://github.com/vinamra1102/HydroLock",
  },
  {
    num: "05",
    slug: "orbit",
    name: "Orbit",
    desc: "My tech stack rendered as an interactive 3D constellation — a navigable node graph of skills and real project history.",
    tech: ["React Three Fiber", "Three.js", "TypeScript"],
    year: "2026",
    category: "frontend",
    gradient: "linear-gradient(135deg, #140f26, #221a3a)",
    repo: "https://github.com/vinamra1102/orbit",
    live: "https://orbit-amber-six.vercel.app/",
    image: "/projects/orbit.png",
  },
  {
    num: "06",
    slug: "sqlite-forensic-recovery",
    name: "SQLite Forensic Recovery",
    desc: "Forensics utility that recovers deleted records straight from SQLite database files — evidence extraction built on real lab experience.",
    tech: ["Python", "SQLite", "Forensics"],
    year: "2025",
    category: "security",
    gradient: "linear-gradient(135deg, #1f1a0a, #302a14)",
    repo: "https://github.com/vinamra1102/sqlite-forensic-recovery-tool",
  },
  {
    num: "07",
    slug: "mintslot",
    name: "MintSlot",
    desc: "Appointment booking platform shipped for a real client — React web app plus Expo Android app, powered by Setmore scheduling.",
    tech: ["React", "Vite", "Expo", "Setmore"],
    year: "2026",
    category: "fullstack",
    gradient: "linear-gradient(135deg, #0a1f1a, #14302a)",
    repo: "https://github.com/vinamra1102/mintSlot",
    live: "https://mintslot-weld.vercel.app/",
    image: "/projects/mintslot.png",
  },
  {
    num: "08",
    slug: "portfolio",
    name: "Portfolio Website",
    desc: "The site you're reading — Next.js and TypeScript with hand-built scroll motion, a scroll-ambience layer, and a sound toggle that stays out of the way.",
    tech: ["Next.js", "TypeScript", "Tailwind", "GSAP", "Framer Motion"],
    year: "2026",
    category: "frontend",
    gradient: "linear-gradient(135deg, #090909, #16181d)",
    repo: "https://github.com/vinamra1102/portfolio",
    live: "https://vinamrabhonsle.online",
    image: "/projects/portfolio.png",
  },
  {
    num: "09",
    slug: "atomity-challenge",
    name: "Atomity Challenge",
    desc: "Drill-down explorer over Kubernetes cloud costs, built for the Atomity frontend challenge — step from cluster to namespace to pod, with proportional bar charts and detail tables at every level.",
    tech: ["Next.js", "TypeScript", "TanStack Query", "Framer Motion"],
    year: "2026",
    category: "frontend",
    gradient: "linear-gradient(135deg, #090909, #101c26)",
    repo: "https://github.com/vinamra1102/atomity-challenge",
    live: "https://atomity-challenge-eight.vercel.app",
    image: "/projects/atomity-challenge.png",
  },
  {
    num: "10",
    slug: "convene",
    name: "Convene",
    desc: "Conference platform with two sides: an installable PWA where attendees build a personal schedule, and an organiser dashboard for events, agendas and live attendance — plus QR passes that keep working when the venue wifi doesn't.",
    tech: ["Next.js", "TypeScript", "Turborepo", "PWA", "Docker"],
    year: "2026",
    category: "fullstack",
    gradient: "linear-gradient(135deg, #090909, #171226)",
    repo: "https://github.com/vinamra1102/Convene",
    live: "https://convene-peach.vercel.app",
    image: "/projects/convene.png",
  },
  {
    num: "11",
    slug: "formforge",
    name: "FormForge",
    desc: "Drag-and-drop form builder SaaS — compose from 12 field types, wire up validation rules and conditional logic, then export as a JSON schema, a React component, or an embed snippet that renders anywhere.",
    tech: ["Next.js", "TypeScript", "Supabase", "Zustand", "dnd-kit"],
    year: "2026",
    category: "fullstack",
    gradient: "linear-gradient(135deg, #090909, #0a1f22)",
    repo: "https://github.com/vinamra1102/FormForge",
    live: "https://formforge-three-lake.vercel.app",
    image: "/projects/formforge.png",
  },
  {
    num: "12",
    slug: "storeiq",
    name: "StoreIQ",
    desc: "Fully client-side rules engine that reads a live shopper session, classifies it into one of five behavioral states, and recommends the next-best action — shipped as a single self-contained React artifact.",
    tech: ["React", "JavaScript"],
    year: "2026",
    category: "frontend",
    gradient: "linear-gradient(135deg, #090909, #0d2018)",
    repo: "https://github.com/vinamra1102/storeiq",
    live: "https://storeiq-lac.vercel.app",
    image: "/projects/storeiq.png",
  },
  {
    num: "13",
    slug: "calculator-net-redesign",
    name: "Calculator.net Redesign",
    desc: "An independent, accessible rebuild of calculator.net — 59+ financial, fitness and everyday calculators on a WCAG-first design system, fixing the 52 issues an audit turned up in the original.",
    tech: ["Next.js", "TypeScript", "Tailwind"],
    year: "2026",
    category: "frontend",
    gradient: "linear-gradient(135deg, #090909, #101430)",
    repo: "https://github.com/vinamra1102/Calculator.net-redesigned-",
    live: "https://calculator-net-redesigned.vercel.app",
    image: "/projects/calculator-net-redesign.png",
  },
  {
    num: "14",
    slug: "nudge",
    name: "Nudge",
    desc: "Landing page for Nudge, a daily matchmaking experience in Bangalore — one match, every evening, with a design-token system built from scratch.",
    tech: ["React", "TypeScript", "Vite", "Tailwind"],
    year: "2026",
    category: "frontend",
    gradient: "linear-gradient(135deg, #090909, #240d18)",
    repo: "https://github.com/vinamra1102/Nudge-Landing-Page",
    live: "https://nudge-landing-six.vercel.app",
    image: "/projects/nudge.png",
  },
  {
    num: "15",
    slug: "resume-website",
    name: "Resume Website",
    desc: "My résumé as a real website — Next.js and Tailwind with scroll-triggered animations and dark/light theming.",
    tech: ["Next.js", "TypeScript", "Tailwind", "Framer Motion"],
    year: "2026",
    category: "frontend",
    gradient: "linear-gradient(135deg, #090909, #0a1e1e)",
    repo: "https://github.com/vinamra1102/resume_profile",
    live: "https://resume-profile-three.vercel.app",
    image: "/projects/resume-website.png",
  },
  {
    num: "16",
    slug: "hasher-tool",
    name: "Hasher Tool",
    desc: "Lightweight Python CLI for generating and verifying file hashes — MD5, SHA-1, SHA-256 and friends — for quick integrity checks.",
    tech: ["Python", "Security"],
    year: "2025",
    category: "security",
    gradient: "linear-gradient(135deg, #090909, #0c210f)",
    repo: "https://github.com/vinamra1102/Hasher-tool",
  },
  {
    num: "17",
    slug: "pong",
    name: "3D Pong",
    desc: "A single-file Python experiment answering one question: what would Pong look like if the paddles left the second dimension?",
    tech: ["Python", "3D"],
    year: "2026",
    category: "fullstack",
    gradient: "linear-gradient(135deg, #090909, #230d0d)",
    repo: "https://github.com/vinamra1102/Pong",
  },
  {
    num: "18",
    slug: "gigfinder",
    name: "GigFinder",
    desc: "Reddit lead scraper for freelance work — sweeps 10 developer subreddits, filters by keyword, and tracks every lead through a Streamlit pipeline from new to contacted to converted.",
    tech: ["Python", "Streamlit", "SQLite", "PRAW"],
    year: "2026",
    category: "fullstack",
    gradient: "linear-gradient(135deg, #090909, #0a1826)",
    repo: "https://github.com/vinamra1102/GigFinder",
  },
  {
    num: "19",
    slug: "shift-cipher",
    name: "ShiftCipher",
    desc: "Terminal Caesar cipher built with Lex and C — a hand-written lexer shifts text by a user-defined key, wrapping the alphabet and preserving case.",
    tech: ["C", "Lex"],
    year: "2026",
    category: "security",
    gradient: "linear-gradient(135deg, #090909, #1a200a)",
    repo: "https://github.com/vinamra1102/ShiftCipher-UsingLex",
  },
  {
    num: "20",
    slug: "food-calorie-estimator",
    name: "Food Calorie Estimator",
    desc: "Streamlit app that identifies food from a photo with a ResNet classifier and returns calories and macros, mapped to a curated set of Indian and international dishes.",
    tech: ["Python", "Streamlit", "ResNet"],
    year: "2026",
    category: "fullstack",
    gradient: "linear-gradient(135deg, #090909, #23120b)",
    repo: "https://github.com/vinamra1102/Food_Calorie_Estimator",
  },
  {
    num: "21",
    slug: "job-scrape",
    name: "Job Scrape",
    desc: "Streamlit dashboard that scrapes and unifies job listings from Internshala, Naukri, CutShort, Wellfound and LinkedIn by role, location and experience.",
    tech: ["Python", "Streamlit", "BeautifulSoup"],
    year: "2025",
    category: "fullstack",
    gradient: "linear-gradient(135deg, #090909, #1c1024)",
    repo: "https://github.com/vinamra1102/Job-Scrape",
  },
  {
    num: "22",
    slug: "port-scanner",
    name: "Port Scanner",
    desc: "Multithreaded Python port scanner that sweeps a host for open ports and reports what's listening.",
    tech: ["Python", "Networking"],
    year: "2025",
    category: "security",
    gradient: "linear-gradient(135deg, #090909, #200f14)",
    repo: "https://github.com/vinamra1102/PortScanner",
  },
];

export const projectFilters: {
  label: string;
  value: "all" | ProjectCategory;
}[] = [
  { label: "All", value: "all" },
  { label: "Security", value: "security" },
  { label: "Frontend", value: "frontend" },
  { label: "Full-Stack", value: "fullstack" },
];
